export const products = [
  {
    sku: '401_1BBXBK',
    name: 'Healthcare Erbology',
    imageUrl: '/assets/images/products/product_1.png',
    category: 'healthcare',
    barcode: 'Ekaterina Tankova',
    oldPrice: 23.99,
    newPrice: 53.99,
    stock: {
      quantity: 85,
      variants: 2,
    },
    status: 1,
  },
  {
    sku: '978_UBFGJC',
    name: 'Makeup Lancome Rouge',
    imageUrl: '/assets/images/products/product_2.png',
    category: 'makeup',
    barcode: '5ece2c0d16f70bff2cf86cd8',
    oldPrice: 23.99,
    newPrice: 53.99,
    stock: {
      quantity: 0,
      variants: 0,
    },
    status: 1,
  },
  {
    sku: '211_QFEXJO',
    name: 'Layering Bracelets Collection',
    imageUrl: '/assets/images/products/product_3.png',
    category: 'makeup',
    barcode: '5ece2c123fad30cbbff8d060',
    oldPrice: 23.99,
    newPrice: 53.99,
    stock: {
      quantity: 45,
      variants: 5,
    },
    status: 0,
  },
  {
    sku: '321_UWEAJT',
    name: 'Skincare Necessaire',
    imageUrl: '/assets/images/products/product_4.png',
    category: 'skincare',
    barcode: '5ece2c1be7996d1549d94e34',
    oldPrice: 23.99,
    newPrice: 53.99,
    stock: {
      quantity: 5,
      variants: 1,
    },
    status: 1,
  },
  {
    sku: '592_LDKDI',
    name: 'Skincare Soja CO',
    imageUrl: '/assets/images/products/product_5.png',
    category: 'skincare',
    barcode: 'b393ce1b09c1254c3a92c827',
    oldPrice: 23.99,
    newPrice: 53.99,
    stock: {
      quantity: 10,
      variants: 1,
    },
    status: 1,
  },
  {
    sku: '324_DKSEKD',
    name: 'Makeup Lipstick',
    imageUrl: '/assets/images/products/product_6.png',
    category: 'makeup',
    barcode: 'a6ede15670da63f49f752c89',
    oldPrice: 23.99,
    newPrice: 53.99,
    stock: {
      quantity: 22,
      variants: 2,
    },
    status: 0,
  },
  {
    sku: '598_DOKEII',
    name: 'Healthcare Ritual',
    imageUrl: '/assets/images/products/product_7.png',
    category: 'healthcare',
    barcode: 'bcad5524fe3a2f8f8620ceda',
    oldPrice: 23.99,
    newPrice: 53.99,
    stock: {
      quantity: 15,
      variants: 1,
    },
    status: 1,
  },
];
