export const DRAWER_MENU_LABEL = {
  DASHBOARD: 'DASHBOARD',
  ACCOUNT: 'ACCOUNT',
  KANBAN: 'KANBAN',
  USER: 'USER',
  PLAY_BACKGROUND: 'PLAY_BACKGROUND',
  PRODUCT: 'PRODUCT',
  PRODUCT_ADD: 'PRODUCT_ADD',
  PRODUCT_LIST: 'PRODUCT_LIST',
  USER_LIST: 'USER_LIST',
  USER_ADD: 'USER_ADD',
};
