export const DRAWER_MENU_LABEL = {
  DASHBOARD: 'DASHBOARD',
  ACCOUNT: 'ACCOUNT',
  KANBAN: 'KANBAN',
  USERS: 'USERS',
  PLAY_BACKGROUND: 'PLAY_BACKGROUND',
  PRODUCT: 'PRODUCT',
  PRODUCT_ADD: 'PRODUCT_ADD',
  PRODUCT_LIST: 'PRODUCT_LIST',
};
