export const PATH = {
  ROOT: '/',
  ERROR_404: '/404',
  ERROR_403: '/403',
  DASHBOARD: '/dashboard',
  PLAY_BACKGROUND: '/playbackground',
  LOGIN: '/login',
  PRODUCT: '/product',
  PRODUCT_LIST: '/product/list',
  PRODUCT_ADD: '/product/add',
  USER: '/user',
  USER_LIST: '/user/list',
  USER_ADD: '/user/add',
  KANBAN: '/kanban',
  ACCOUNT: '/account',
  EDIT: '/edit',
};
