export const AuthActionTypes = {
  LOGIN_REQUEST: 'AUTH/LOGIN_REQUEST',
  LOGIN_SUCCESS: 'AUTH/LOGIN_SUCESS',
  LOGIN_FAILURE: 'AUTH/LOGIN_FAILURE',
  SILENT_LOGIN: 'AUTH/SILENT_LOGIN',
  REGISTER_REQUEST: 'AUTH/REGISTER_REQUEST',
  REGISTER_SUCCESS: 'AUTH/REGISTER_SUCESS',
  REGISTER_FAILURE: 'AUTH/REGISTER_FAILURE',
  LOGOUT: 'AUTH/LOGOUT',
  CHECK_USER_SESSION: 'AUTH/CHECK_USER_SESSION',
};
